### ISSUE TITLE
fast read

### ISSUE THREAD

**Issue by lrotava** [rftafas/stdcores#1]
Opa, to tentando usar o fast_read aqui e aparentemente ele nao faz a leitura no AXI-M, só fica jogando o ACK pra fora
fiz uma simulacao, segue o waveform (já que voce gosta muito de waveform :) ):
![image](https://user-images.githubusercontent.com/29836682/87947237-569f9380-caa3-11ea-88f1-5438f6500035.png)

to fazendo alguma coisa errada?

**Comment by lrotava** [comment]
#3 i made some changes i believe help with this issue.

**Comment by rftafas** [comment]
solved with #5

**Comment by rftafas** [comment]
Was not solved. Working on it. It should wait a full SPI byte on ACK to give at least 8 SPI cycles for AXI to read the data. This was fixed. Reading is still bogus.

**Comment by rftafas** [comment]
Fixed directly on master (my bad! :D). Now desired behavior is in place. Note that after address, slave sends an AC (the closes to ACK) confirming a fast_read.
