### ISSUE TITLE
sclk frequency

### ISSUE THREAD

**Issue by lrotava** [rftafas/stdcores#17]
Hi, me again
what is the theoretical max sclk frequency for this block? In native and in oversampled modes.

In my tests, axi clk is 100 Mhz, with sclk in 12 MHz the reads lose the first byte for each word. There is a latency in between the act_st and the wait4spi_st (when it puts the value on spi_txdata_o). When the spi is a bit faster, this is enough for the state machine to lose the first spi_txen_i = 1.
In the oversampled mode only the fast read is working in my tests. In the normal read, the first bit in the first byte can come wrong, but i did not have time to investigate it.

**Comment by rftafas** [comment]
On both modes it depends on how is the AXI replies and how fast the AXI Slave replies for an AXI Read.

That said, on the best case scenario, MCLK > 4*SCLK to use regular read and write.

---

You can get better if you try only using FAST_READ and FAST_WRITE. ACK cycle gives some refresh to the AXI maxines (and that is why it forces some different behavior during Wait4SPI). In this case, MCLK >= SCLK.

---

Oversample mode: I haven't tested it yet but is should be even slower then native mode. Something along MCLK > 8*SCLK.

BTW: it is a bug if oversampled mode cannot work with regular read and write. Please, open an issue for this.

**Comment by rftafas** [comment]
BTW, I'm studying to add nSPI (dual, quad, octal) support so it will have decent bandwidth even in the case of lower clocks.
