### ISSUE TITLE
BRESP and RRESP

### ISSUE THREAD

**Issue by lrotava** [rftafas/stdcores#4]
If my slave leaves the xRESP signal in an error state when in Idle, during the next operation, the master will accuse error immediately, not waiting for the xVALID signal to go high.

> if M_AXI_BVALID = '1' and M_AXI_BRESP(1) = '0' then
	   mst_exec_state <= BUS_DONE;
	M_AXI_BREADY   <= '0';
**elsif M_AXI_BRESP(1) = '1' then**
	mst_exec_state <= BUS_DONE;
	M_AXI_BREADY   <= '0';
	bus_error_o    <= '1';
else
	mst_exec_state <= INIT_WRITE;
end if;`

I changed the behavior of the slave to keep the RESP in OK when idle, and only set the error when VALID is high, then it works ok, but should this piece of the AXI master be changed?

**Comment by rftafas** [comment]
solved with #5
